# This file uses the built in $aadToken feature Visual Studio Code of REST Client extension
# This approach does not work in Visual Studio

@baseUrl = https://dkdt-dev-1.crm.dynamics.com/api/data/v9.2

### WhoAmI
GET {{baseUrl}}/WhoAmI
Authorization: {{$aadToken 77f7d709-77d9-4511-9d3d-f33e5ea1c963}}

### Get all users with domainname containing '@devkeydet.onmicrosoft.com'
### and return fullname, domainname and azureactivedirectoryobject to keep the response small
GET {{baseUrl}}/systemusers?$filter=contains(domainname,'@devkeydet.onmicrosoft.com')&$select=fullname,domainname,azureactivedirectoryobjectid
Authorization: {{$aadToken 77f7d709-77d9-4511-9d3d-f33e5ea1c963}}

### Share connection reference with a user using the GrantAccess action
POST {{baseUrl}}/GrantAccess
Authorization: {{$aadToken 77f7d709-77d9-4511-9d3d-f33e5ea1c963}}
Content-Type: application/json

{
  "Target": {
    "@odata.type": "Microsoft.Dynamics.CRM.connectionreference",
    "connectionreferenceid": "your-guid"
  },
  "PrincipalAccess": {
    "AccessMask": "ReadAccess",
    "Principal": {
      "@odata.type": "Microsoft.Dynamics.CRM.systemuser",
      "systemuserid": "your-guid"
    }
  }
}