# This file depends on running the create-or-update-env-file.ps1 first to put the bearer token in the .env file 
# This approach works in Visual Studio as well as in Visual Studio Code

### WhoAmI
GET {{$dotenv baseUrl}}/WhoAmI
Authorization: Bearer {{$dotenv accessToken}}

### Get all users with domainname containing '@devkeydet.onmicrosoft.com'
### and return fullname, domainname and azureactivedirectoryobject to keep the response small
GET {{$dotenv baseUrl}}/systemusers?$filter=contains(domainname,'@devkeydet.onmicrosoft.com')&$select=fullname,domainname,azureactivedirectoryobjectid
Authorization: Bearer {{$dotenv accessToken}}

### Share connection reference with a user using the GrantAccess action
POST {{$dotenv baseUrl}}/GrantAccess
Authorization: Bearer {{$dotenv accessToken}}
Content-Type: application/json

{
  "Target": {
    "@odata.type": "Microsoft.Dynamics.CRM.connectionreference",
    "connectionreferenceid": "your-guid"
  },
  "PrincipalAccess": {
    "AccessMask": "ReadAccess",
    "Principal": {
      "@odata.type": "Microsoft.Dynamics.CRM.systemuser",
      "systemuserid": "your-guid"
    }
  }
}